/bin/sh: /Users/tanishkothari/.pyenv/versions/3.10.12/bin/bench: No such file or directory
/bin/sh: /Users/tanishkothari/frappe_env/bin/bench: No such file or directory
Backup failed for Site testsite.com. Database or site_config.json may be corrupted
Backup failed for Site testsite.com. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 837, in backup
    odb = scheduled_backup(
      context = {'sites': ['testsite.com'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x111f29120>
      exit_code = 0
      rollback_callback = None
      site = 'testsite.com'
  File "apps/frappe/frappe/utils/backups.py", line 577, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1120a64d0>
  File "apps/frappe/frappe/utils/backups.py", line 635, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1120a64d0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 516, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>>
      paths = ('./testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz',)
      path = './testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 511, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>>
      paths = ('./testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz',)
      path = './testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 453, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x105b1e5d0>
      shlex = <module 'shlex' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1056d9a80>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x111f67b00>
      bin = None
      args = ['--user=_7de53a30147f5e16', '--host=127.0.0.1', '--port=3306', '--password=sBGqCkHwhQl2qRAg', '--single-transaction', '--quick', '--lock-tables=false', '_7de53a30147f5e16']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1056d96c0>
      inspect = <module 'inspect' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '8bc9ede997df67eefdc17d95b140f9e560a92fa50b7ff0b0ba2f1d3f'}
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '8bc9ede997df67eefdc17d95b140f9e560a92fa50b7ff0b0ba2f1d3f'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 837, in backup
    odb = scheduled_backup(
      context = {'sites': ['testsite.com'], 'force': False, 'verbose': True, 'profile': False}
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x107c6d120>
      exit_code = 0
      rollback_callback = None
      site = 'testsite.com'
  File "apps/frappe/frappe/utils/backups.py", line 577, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x111fa25c0>
  File "apps/frappe/frappe/utils/backups.py", line 635, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x111fa25c0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x107d05700>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x107d05700>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 516, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x107d05700>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x107d05700>>
      paths = ('./testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz',)
      path = './testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 511, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x107d05700>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x107d05700>>
      paths = ('./testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz',)
      path = './testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 453, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x107d05700>
      shlex = <module 'shlex' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/shlex.py'>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      get_app_branch = <function get_app_branch at 0x1062b9a80>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./testsite.com/private/backups/20240530_180002-testsite_com-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x107cafb00>
      bin = None
      args = ['--user=_7de53a30147f5e16', '--host=127.0.0.1', '--port=3306', '--password=sBGqCkHwhQl2qRAg', '--single-transaction', '--quick', '--lock-tables=false', '_7de53a30147f5e16']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/__init__.py", line 681, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/__init__.py", line 646, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1062b96c0>
      inspect = <module 'inspect' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '03f2e3ccf4a3bc78e5d4d61cbc1b2097b55e5806b718a3c47d8d2d32'}
  File "apps/frappe/frappe/__init__.py", line 597, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '03f2e3ccf4a3bc78e5d4d61cbc1b2097b55e5806b718a3c47d8d2d32'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
